### PR TITLE
Made the game into a state based game.

### PR DESCRIPTION
**Pull request by Jonagoo**
Major revamp to how to game works, it is now a state based game, but the only changes are in the Game class (and the new Play/Menu classes). The game now has a menu screen, which is loaded by default when starting the game and can display controls and start up the game. Also added background/gamename.

### CODE REVIEW

**Comment by Jonagoo** [comment]
I removed the knockback on getting hit. It was working pretty poorly and isn't that great of a mechanic anyway imo, since we have hitstun as well.

**Comment by Nellta** [comment]
I used that for my boss fight. I have no idea how it affects it since the game is now twice as hard and I can't reach the last map at all.

**Comment by Jonagoo** [comment]
The code is still there, if you need it, just commented.

**Comment by Nellta** [comment]
k, because I managed to reach the boss and yup, I need it.

**Comment by Jonagoo** [comment]
The biggest factor in zombie difficulti i believe is the hitstun/invulnerability, the knockback only affects if since they have to run back a bit, but if we increase hitstun/reduce invulnerability it should do the same. The knockback code works a bit shitty since it won't a) knockback the player while attacking, and b) knockback until after the hitstun is complete, and it and hitstun basically does the same for gameplay purposes (making sure you aren't taking guaranteed damage from monsters) so I think one or the other is fine. What was it used in the bossfight for?

**Comment by Nellta** [comment]
If the boss is hit he  will fly back to the other wall and stay there until the player goes after him, meaning the player has to run past his zombie minions. As long as that can be kept without using the knockback then I have no problems with removing it and adjusting the hitstun/invulnerability. After all, it IS kind of buggy at best.

**Pull request merged**
