### PR TITLE
Bossfights and objects along the maps

### PR DESCRIPTION
**Pull request by Nellta**
I looked at you branch and we have some conflicts with rendering, since I added a objectlayer, which needs to be rendered after the player to avoid some rendering issues. To do that I added a method to render the new layer "Object".

Btw, jag dör nu konstant innan jag hinner till bossen, jag tror att knockback hjälpte med det.

### CODE REVIEW

**Comment by Jonagoo** [comment]
I can't find data/explosives.png or data/boss.png in the files, did you add them to the commit?

**Comment by Nellta** [comment]
ups, they were outside of the map folder so I missed them. Will fix immediately

**Comment by Jonagoo** [comment]
Your second commit removed the game, level and room class.

**Comment by Nellta** [comment]
seriously?...

**Comment by Jonagoo** [comment]
Created a new branch with all the files included

**Pull request closed without merging**
